version: '3.8'

services:
  db:
    container_name: mongodb
    image: mongo
    command: mongod --port 27017
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      cn-bridge:
        aliases:
          - db

  free5gc-nrf:
    container_name: nrf
    image: free5gc/nrf:v3.4.1
    command: ./nrf -c ./config/nrfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      cn-bridge:
        aliases:
          - nrf.free5gc.org
    depends_on:
      - db

  free5gc-amf:
    container_name: amf
    image: free5gc/amf:v3.4.1
    command: ./amf -c ./config/amfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/amfcfg.yaml:/free5gc/config/amfcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      cn-bridge:
        ipv4_address: 10.100.200.131
        aliases:
          - amf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    container_name: ausf
    image: free5gc/ausf:v3.4.1
    command: ./ausf -c ./config/ausfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      cn-bridge:
        aliases:
          - ausf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    container_name: nssf
    image: free5gc/nssf:v3.4.1
    command: ./nssf -c ./config/nssfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      cn-bridge:
        aliases:
          - nssf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    container_name: pcf
    image: free5gc/pcf:v3.4.1
    command: ./pcf -c ./config/pcfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      cn-bridge:
        aliases:
          - pcf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-smf:
    container_name: smf
    image: free5gc/smf:v3.4.1
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    expose:
      - "8000"
    volumes:
      - ./config/smfcfg.yaml:/free5gc/config/smfcfg.yaml
      - ./config/uerouting.yaml:/free5gc/config/uerouting.yaml
    environment:
      GIN_MODE: release
    networks:
      cn-bridge:
        aliases:
          - smf.free5gc.org
    depends_on:
      - free5gc-nrf
      - free5gc-upf

  free5gc-udm:
    container_name: udm
    image: free5gc/udm:v3.4.1
    command: ./udm -c ./config/udmcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udmcfg.yaml:/free5gc/config/udmcfg.yaml
    environment:
      GIN_MODE: release
    networks:
      cn-bridge:
        aliases:
          - udm.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-udr:
    container_name: udr
    image: free5gc/udr:v3.4.1
    command: ./udr -c ./config/udrcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udrcfg.yaml:/free5gc/config/udrcfg.yaml
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      cn-bridge:
        aliases:
          - udr.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-chf:
    container_name: chf
    image: free5gc/chf:v3.4.1
    command: ./chf -c ./config/chfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/chfcfg.yaml:/free5gc/config/chfcfg.yaml
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      cn-bridge:
        aliases:
          - chf.free5gc.org
    depends_on:
      - db
      - free5gc-nrf
      - free5gc-webui

  free5gc-webui:
    container_name: webui
    image: free5gc/webui:v3.4.1
    command: ./webui -c ./config/webuicfg.yaml
    expose:
      - "2122"
      - "2121"
    volumes:
      - ./config/webuicfg.yaml:/free5gc/config/webuicfg.yaml
    environment:
      - GIN_MODE=release
    networks:
      cn-bridge:
        aliases:
          - webui
    ports:
      - "5000:5000"
      - "2122:2122"
      - "2121:2121"
    depends_on:
      - db
      - free5gc-nrf

  free5gc-upf:
    container_name: upf
    image: free5gc/upf:v3.4.1
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/upfcfg.yaml:/free5gc/config/upfcfg.yaml
      - ./config/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      cn-bridge:
        aliases:
          - upf.free5gc.org
      tsn-bridge-in:
        ipv4_address: 10.100.201.100

  oai-gnb:
    image: oaisoftwarealliance/oai-gnb:develop
    privileged: true
    container_name: oai-gnb
    environment:
        USE_ADDITIONAL_OPTIONS: --sa -E --rfsim --log_config.global_log_options level,nocolor,time
        ASAN_OPTIONS: detect_leaks=0
    depends_on:
      - free5gc-amf
      - free5gc-upf
    networks:
      cn-bridge:
        ipv4_address: 10.100.200.140
    volumes:
        - ./config/gnb.sa.band78.106prb.rfsim.conf:/opt/oai-gnb/etc/gnb.conf
    healthcheck:
        test: /bin/bash -c "pgrep nr-softmodem"
        interval: 10s
        timeout: 5s
        retries: 5

  oai-nr-ue:
    image: oai-nr-ue:develop
    privileged: true
    container_name: oai-nr-ue
    environment:
        USE_ADDITIONAL_OPTIONS: -E --sa --rfsim -r 106 --numerology 1 --uicc0.imsi 208930000000001 -C 3619200000 --rfsimulator.serveraddr 10.100.200.140 --log_config.global_log_options level,nocolor,time
    depends_on:
        - oai-gnb
    networks:
      cn-bridge:
        ipv4_address: 10.100.200.150
      tsn-bridge-out:
        ipv4_address: 10.100.202.100
    volumes:
        - ./config/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
    healthcheck:
        test: /bin/bash -c "pgrep nr-uesoftmodem"
        interval: 10s
        timeout: 5s
        retries: 5

  ptp-master:
    container_name: ptp-master 
    entrypoint: /bestvibes-ptp/master/master.out
    networks:
      tsn-bridge-in:
        ipv4_address: 10.100.201.200
    build:
      context: ./ptp-emulator
    expose:
      - "2468"

  ptp-slave:
    container_name: ptp-slave 
    entrypoint: /bestvibes-ptp/slave/slave.out
    networks:
      tsn-bridge-out:
        ipv4_address: 10.100.202.200
    build:
      context: ./ptp-emulator
    expose:
      - "2468"
    
networks:
  cn-bridge:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

  tsn-bridge-in: # Base Station Side
    ipam:
      driver: default
      config:
        - subnet: 10.100.201.0/24
    driver_opts:
      com.docker.network.bridge.name: tsn-br-in 

  tsn-bridge-out: # UE Side
    ipam:
      driver: default
      config:
        - subnet: 10.100.202.0/24
    driver_opts:
      com.docker.network.bridge.name: tsn-br-out

volumes:
  dbdata:
