version: '3.8'

services:
  ptp-master:
    container_name: ptp-master 
    networks:
      privnet:
        ipv4_address: 10.100.200.210
        aliases:
          - ptpmaster.org
    build:
      context: ./

  ptp-slave:
    container_name: ptp-slave 
    networks:
      privnet:
        ipv4_address: 10.100.200.220
        aliases:
          - ptpmaster.org
    build:
      context: ./
    
networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

volumes:
  dbdata:
