# This dockerfile is for testing only the ptp service
# These containers are also included in the main docker-compose.yml
version: '3.8'

services:
  ptp-master:
    container_name: ptp-master-test
    entrypoint: /bestvibes-ptp/master/master.out
    networks:
      privnet:
        ipv4_address: 10.100.99.210
        aliases:
          - master.ptp.org
    build:
      context: ./
    expose:
      - "2468"

  ptp-slave:
    container_name: ptp-slave-test
    entrypoint: /bestvibes-ptp/slave/slave.out
    networks:
      privnet:
        ipv4_address: 10.100.99.220
        aliases:
          - slave.ptp.org
    build:
      context: ./
    expose:
      - "2468"
    
networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.99.0/24

volumes:
  dbdata:
