# This dockerfile is for testing only the ptp service
# These containers are also included in the main docker-compose.yml
version: '3.8'

services:
  ptp-master:
    container_name: ptp-master 
    entrypoint: /bestvibes-ptp/master/master.out
    networks:
      privnet:
        ipv4_address: 10.100.200.210
        aliases:
          - master.ptp.org
    build:
      context: ./
    expose:
      - "2468"

  ptp-slave:
    container_name: ptp-slave 
    entrypoint: /bestvibes-ptp/slave/slave.out
    networks:
      privnet:
        ipv4_address: 10.100.200.220
        aliases:
          - slave.ptp.org
    build:
      context: ./
    expose:
      - "2468"
    
networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc

volumes:
  dbdata:
